return {}
-- return {
-- 	"rose-pine/neovim",
-- 	name = "rose-pine",
-- 	lazy = false,
-- 	config = function()
-- 		require("rose-pine").setup({
-- 			variant = "auto", -- auto, main, moon, or dawn
-- 			dark_variant = "moon", -- main, moon, or dawn
-- 			dim_inactive_windows = false,
-- 			extend_background_behind_borders = true,
-- 			styles = {
-- 				transparency = false,
-- 			},
-- 			highlight_groups = {
-- 				CurSearch = { fg = "base", bg = "leaf", inherit = false },
-- 				Search = { fg = "text", bg = "leaf", blend = 20, inherit = false },
-- 			},
-- 		})
-- 		vim.cmd("colorscheme rose-pine")
-- 	end,
-- }
